package org.example.illuminatiadminbot.inbound.menu;

public enum MenuState {
    MAIN_MENU,
    SUBSCRIPTION_MENU,
    DURATION_MENU,
    NICK_OR_PHONE_MENU,
    SUBSCRIBER_ID_MENU,
    BY_PHONE_MENU,
    THEME_MENU,
    UPLOAD_MENU,
    FILE_MENU,
    DESCRIPTION_MENU,
    ADMIN_MENU,
    APPOINTMENT_MENU,
    DISMISSAL_MENU,
    BAN_MENU,
    SHOW_SQL_MENU,
    SHOW_SUPERGROUPS_MENU
}
